/***********************************************\
* plain format import module                    *
* selector function version                     *
* (C) 2005 Pavel Strachota                      *
* file: plain_importS.c                         *
\***********************************************/
#include "common.h"
#include "dataIO.h"

#include <stdio.h>

int plain_importS(void (*data)(int,SCALAR_DATA),SCALAR_TYPE type,int max_read,_conststring_ path)
/*
imports the data of the given type from the plain ASCII format generated by plain_export/gnuplot_export.

it skips the first line and then reads a maximum of 'max_read' values.

this version uses the selector function 'data()' which takes an integer argument specifying the ordinal
number (starting from 0) of the imported data element (value) and a SCALAR_DATA union that contains this value.
The 'data()' function should then process the retrieved value or store it somewhere (not in a linear array - if
you want to do this, you'd better use the plain_import() function, which is faster). The appropriate member
of the union set by plain_importS() (and thus the appropriate type of the actually imported data) is determined
by the 'type' parameter.

return codes:
values read	success
-1		file access error
-3		'max_read' <= 0 or 'data' is a null pointer
*/
{
 	FILE * infile;
	int r,tr;
	char buf[256];

	SCALAR_DATA d;

	if(max_read<=0 || data==NULL) return(-3);

	infile=fopen(path,"r");
	if(!infile) return(-1);

	fgets(buf,255,infile);		/* skip the first line */

	tr=r=0;
	switch(type) {						/* EOF is -1 */
		case SCALAR_int:
				while((max_read--)) {
					if(fscanf(infile,"%d",&(d.int_data))==EOF) break;
					data(tr,d);
					tr++;
				}
				break;
		case SCALAR_FLOAT:
				while((max_read--)) {
					if(fscanf(infile,"%" iFTC_g,&(d.FLOAT_data))==EOF) break;
					data(tr,d);
					tr++;
				}
				break;
		case SCALAR_double:
				while((max_read--)) {
					if(fscanf(infile,"%lg",&(d.double_data))==EOF) break;
					data(tr,d);
					tr++;
				}
	}

	fclose(infile);
	return(tr);
}
