/***********************************************\
* plain format import module                    *
* (C) 2005 Pavel Strachota                      *
* file: plain_import.c                          *
\***********************************************/
#include "common.h"
#include "dataIO.h"

#include <stdio.h>

int plain_import(void * data,SCALAR_TYPE type,int max_read,_conststring_ path)
/*
imports the data of the given type from the plain ASCII format generated by plain_export/gnuplot_export.

it skips the first line and then reads a maximum of 'max_read' values into the array 'data'.
control of the array dimensions is up to user's responsibility.

return codes:
values read	success
-1		file access error
-3		'max_read' <= 0 or 'data' is a null pointer
*/
{
 	FILE * infile;
	int r,tr;
	char buf[256];

        int * int_data=(int *)data;
        FLOAT * FLOAT_data=(FLOAT *)data;
        double * double_data=(double *)data;

	if(max_read<=0 || data==NULL) return(-3);

	infile=fopen(path,"r");
	if(!infile) return(-1);

	fgets(buf,255,infile);		/* skip the first line */

	tr=r=1;
	switch(type) {						/* EOF is -1 */
		case SCALAR_int:
				while((max_read--) && r!=EOF)
					tr+=(r=fscanf(infile,"%d",int_data++));
				break;
		case SCALAR_FLOAT:
				while((max_read--) && r!=EOF)
					tr+=(r=fscanf(infile,"%" iFTC_g,FLOAT_data++));
				break;
		case SCALAR_double:
				while((max_read--) && r!=EOF)
					tr+=(r=fscanf(infile,"%lg",double_data++));
	}

	/* in case the loop ended because of 'max_read': 'tr' was not decreased */
	if(r!=EOF) tr--;

	fclose(infile);
	return(tr);
}
